version: '3.3'

services:
  web:
    image: medstoun/cw4_docker
    build: .
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: flask_app_password
      POSTGRES_DB: flask_app
